# Jekyll configuration
name: OBO-Data-Converter
description: Utility for converting ontology OBO files to a tab-delimited text file
url: https://pnnl-comp-mass-spec.github.io/OBO-Data-Converter/

# Google Analytics
google_analytics: G-LXXKP1N66C
